/* Auto-generated by genmsg_cpp for file /home/diego/fuerte_workspace/sandbox/aibo_server/msg/Bumper.msg */
#ifndef AIBO_SERVER_MESSAGE_BUMPER_H
#define AIBO_SERVER_MESSAGE_BUMPER_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace aibo_server
{
template <class ContainerAllocator>
struct Bumper_ {
  typedef Bumper_<ContainerAllocator> Type;

  Bumper_()
  : header()
  , is_pressed(false)
  {
  }

  Bumper_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , is_pressed(false)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef uint8_t _is_pressed_type;
  uint8_t is_pressed;


  typedef boost::shared_ptr< ::aibo_server::Bumper_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::aibo_server::Bumper_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Bumper
typedef  ::aibo_server::Bumper_<std::allocator<void> > Bumper;

typedef boost::shared_ptr< ::aibo_server::Bumper> BumperPtr;
typedef boost::shared_ptr< ::aibo_server::Bumper const> BumperConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::aibo_server::Bumper_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::aibo_server::Bumper_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace aibo_server

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::aibo_server::Bumper_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::aibo_server::Bumper_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::aibo_server::Bumper_<ContainerAllocator> > {
  static const char* value() 
  {
    return "7feed261fab09e5d0ce6318f9f9ed4b9";
  }

  static const char* value(const  ::aibo_server::Bumper_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x7feed261fab09e5dULL;
  static const uint64_t static_value2 = 0x0ce6318f9f9ed4b9ULL;
};

template<class ContainerAllocator>
struct DataType< ::aibo_server::Bumper_<ContainerAllocator> > {
  static const char* value() 
  {
    return "aibo_server/Bumper";
  }

  static const char* value(const  ::aibo_server::Bumper_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::aibo_server::Bumper_<ContainerAllocator> > {
  static const char* value() 
  {
    return "#ROS header\n\
Header header\n\
\n\
#Whether the bumper is being pressed\n\
bool is_pressed\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::aibo_server::Bumper_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::aibo_server::Bumper_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::aibo_server::Bumper_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::aibo_server::Bumper_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.is_pressed);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Bumper_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::aibo_server::Bumper_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::aibo_server::Bumper_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "is_pressed: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_pressed);
  }
};


} // namespace message_operations
} // namespace ros

#endif // AIBO_SERVER_MESSAGE_BUMPER_H

