/* Auto-generated by genmsg_cpp for file /home/diego/fuerte_workspace/sandbox/aibo_server/msg/Sound.msg */
#ifndef AIBO_SERVER_MESSAGE_SOUND_H
#define AIBO_SERVER_MESSAGE_SOUND_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace aibo_server
{
template <class ContainerAllocator>
struct Sound_ {
  typedef Sound_<ContainerAllocator> Type;

  Sound_()
  : header()
  , sound_values()
  {
  }

  Sound_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , sound_values(_alloc)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _sound_values_type;
  std::vector<double, typename ContainerAllocator::template rebind<double>::other >  sound_values;


  typedef boost::shared_ptr< ::aibo_server::Sound_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::aibo_server::Sound_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Sound
typedef  ::aibo_server::Sound_<std::allocator<void> > Sound;

typedef boost::shared_ptr< ::aibo_server::Sound> SoundPtr;
typedef boost::shared_ptr< ::aibo_server::Sound const> SoundConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::aibo_server::Sound_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::aibo_server::Sound_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace aibo_server

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::aibo_server::Sound_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::aibo_server::Sound_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::aibo_server::Sound_<ContainerAllocator> > {
  static const char* value() 
  {
    return "bbf293403e3416f706e3acde83c58590";
  }

  static const char* value(const  ::aibo_server::Sound_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xbbf293403e3416f7ULL;
  static const uint64_t static_value2 = 0x06e3acde83c58590ULL;
};

template<class ContainerAllocator>
struct DataType< ::aibo_server::Sound_<ContainerAllocator> > {
  static const char* value() 
  {
    return "aibo_server/Sound";
  }

  static const char* value(const  ::aibo_server::Sound_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::aibo_server::Sound_<ContainerAllocator> > {
  static const char* value() 
  {
    return "#ROS header\n\
Header header\n\
\n\
#Whether the bumper is being pressed\n\
float64[] sound_values\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::aibo_server::Sound_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::aibo_server::Sound_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::aibo_server::Sound_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::aibo_server::Sound_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.sound_values);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Sound_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::aibo_server::Sound_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::aibo_server::Sound_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "sound_values[]" << std::endl;
    for (size_t i = 0; i < v.sound_values.size(); ++i)
    {
      s << indent << "  sound_values[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.sound_values[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // AIBO_SERVER_MESSAGE_SOUND_H

