(cl:in-package aibo_server-msg)
(cl:export '(JOINTLF1-VAL
          JOINTLF1
          JOINTLF2-VAL
          JOINTLF2
          JOINTLF3-VAL
          JOINTLF3
          JOINTLH1-VAL
          JOINTLH1
          JOINTLH2-VAL
          JOINTLH2
          JOINTLH3-VAL
          JOINTLH3
          JOINTRF1-VAL
          JOINTRF1
          JOINTRF2-VAL
          JOINTRF2
          JOINTRF3-VAL
          JOINTRF3
          JOINTRH1-VAL
          JOINTRH1
          JOINTRH2-VAL
          JOINTRH2
          JOINTRH3-VAL
          JOINTRH3
          TAILPAN-VAL
          TAILPAN
          TAILTILT-VAL
          TAILTILT
          HEADTILT-VAL
          HEADTILT
          HEADPAN-VAL
          HEADPAN
          HEADNECK-VAL
          HEADNECK
          MOUTH-VAL
          MOUTH
))